---
title: "Rolling Stone 200 Rock Corpus - Melody Analysis"
author: "Ethan Mallove"
date: "12/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r melodyAnalysis}

# Generate a file
#   cat song.mel | src/get-notes-from-melody-file.pl > all-notes.txt
#
#  Tidy up the data file, so that each space-separated note value matches /b?[1-7]/
#
fileName <- 'all-notes.txt'
v <- readChar(fileName, file.info(fileName)$size)
all_notes <- strsplit(v, split=" ")

# FIXME: make it so we don't have a double subscript operator here [[]]
all_notes_table <- table(all_notes[[1]])
notes_in_corpus_count <- length(all_notes[[1]])

# FIXME: counts() function?
# counts(all_notes[[1]])

hist(as.numeric(all_notes[[1]]))
# barplot(all_notes)
```

```{r sumOfNoteProbabilities}

# Given the following probabilities:
#   > (all_notes_table[["1"]] / sum(all_notes_table))
#   [1] 0.2639584
#   > (all_notes_table[["b2"]] / sum(all_notes_table))
#   [1] 0.0004593243
# Range of this function is 0.0004593243 - 0.2639584

getAverageNoteProbability <- function (notes, corpus_notes_table) {
  sum_of_probabilities = 0
  for (n in notes) {
    
    # DEBUGGING
    # print (paste("note P(x) = ", (corpus_notes_table[[n]] / (sum(corpus_notes_table)))))
    sum_of_probabilities = sum_of_probabilities + (corpus_notes_table[[n]] / sum(corpus_notes_table))
  }
  return (sum_of_probabilities / length(notes))
}

```

```{r songs}
mat <- read.csv("song-notes.csv", row.names=1)

note_probability_scores <- matrix()

# Compute average note probability for each song
#for (song in rownames(mat)[1:3]) {   # DEBUGGING
for (song in rownames(mat)) {
  #print(song)
  #print(mat[song,])
  notes <- strsplit(x = as.character(mat[song,]), split = " ")
  
  # FIXME: again, remove unnessary subscripting[[]] here
  note_probability_scores[song] <- getAverageNoteProbability(notes[[1]], all_notes_table)
}

```